apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    run: mysql
spec:
  volumes:
    - name: secret-volume
      emptyDir: {} 

  initContainers:
    - name: secrets
      image: amazon/aws-cli
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "us-east-1"
      command:
        - /bin/sh
        - -c
        - |
          yum install -y jq && \
          mkdir -p /secrets && \
          aws sts get-caller-identity && \
          aws secretsmanager get-secret-value --region us-east-1 --secret-id wordpress-secrets --query 'SecretString' --output text | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' > /secrets/secret.properties
      volumeMounts:
        - name: secret-volume
          mountPath: /secrets

  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306
      command:
        - /bin/sh
        - -c
        - |
          export $(cat /secrets/secret.properties | xargs) && docker-entrypoint.sh mysqld
      env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: mysql_user
      volumeMounts:
        - name: secret-volume
          mountPath: /secrets
