apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    run: wp
spec:
  volumes:
    - name: secret-volume
      emptyDir: {} 

  initContainers:
    - name: init-secrets
      image: amazon/aws-cli
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "us-east-1"
      command:
        - /bin/sh
        - -c
        - |
          yum install -y jq && \
          mkdir -p /secrets && \
          aws sts get-caller-identity && \
          aws secretsmanager get-secret-value --region us-east-1 --secret-id wordpress-secrets --query 'SecretString' --output text | \
          jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' > /secrets/secret.properties
      volumeMounts:
        - name: secret-volume
          mountPath: /secrets

  containers:
    - name: wordpress
      image: wordpress:latest
      ports:
        - containerPort: 80
      command:
        - /bin/sh
        - -c
        - |
          export $(cat /secrets/secret.properties | xargs) && docker-entrypoint.sh apache2-foreground
      env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: wordpress_db_host
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: wordpress_db_user
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: wordpress_db_name
      volumeMounts:
        - name: secret-volume
          mountPath: /secrets
          
