apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: john-pod-list-reader
  namespace: default
subjects:
  - kind: User
    name: aizen       
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-pod

