apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command: ["sh", "-c", "echo Backing up database...; sleep 10; echo Database backed up!"]
          restartPolicy: OnFailure