apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: wordpress_db_host
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: wordpress_db_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: wordpress_db_password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: wordpress_db_name
         
