apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  mysql_root_password: d29yZHByZXNzQDEyMw==
  wordpress_db_password: d29yZHByZXNzQDEyMw==
  mysql_password: d29yZHByZXNzQDEyMw==
